export const DATA = [
    {
        id: 1,
        data1: 'Bluetooth Version',
        data2: 'Size(main Display)',
        data3: 'CPU Speed',
        data4: 'OS',
        data5: 'Display',
        data6: 'Memoria',
        data7: 'Sensores',
        data8: 'Material De la Malla',
        data9: 'loren ipsum',
        data10: 'loren ipsum',
        text1: 'Bluetooth v5.0',
        text2: '1.4" (34.5mm)',
        text3: '1.15GHz',
        text4: 'Tizen',
        text5: 'Super AMOLED',
        text6: 'RAM 1 gb',
        text7: 'Accelerometer,Barometer,Gyro Sensor,Light ',
        text8: 'Pvc refornzado',
        text9: 'loren ipsum',
        text10: 'loren ipsum',
    },
];
